# Server defaults.
#watch: false # deprecated
#server: false # deprecated
#auto: true # deprecated
port: 4000

# Project defaults.
#markdown: redcarpet
markdown: kramdown
pygments: false
lsi: false
safe: false

#permalink: /news/:year/:month/:day/:title.html

exclude: ["node_modules", "README.md", "Gruntfile.js", "package.json"]

kramdown:
  toc_levels: "2,3"

# Site globals used throughout docs.
load_platform: true
project_title: Polymer
latest_version: 0.0.20130905
add_permalinks: true # adds permalinks to heading tags.
load_disqus: true

authors:
  ebidel:
    full_name: Eric Bidelman
    gplus: 118075919496626375791
    web: http://www.ericbidelman.com
    twitter: ebidel
    github: ebidel