markdown: kramdown
highlighter: null #pygments
lsi: false
safe: false

#permalink: /news/:year/:month/:day/:title.html

exclude: ["node_modules", "scripts", "sass", "app.yaml", "README.md",
          "CONTRIBUTING.md", "Gruntfile.js", "package.json", "config.rb",
          "build.py", "polymer-all", "components"]

kramdown:
  toc_levels: 2..3
  #auto_ids: true

  #input: GFM # enable github flavored markdown
  # use_coderay: true
  # coderay:
  #   coderay_line_numbers: nil
  #   coderay_css: style

# Site globals used throughout docs.
project_title: Polymer
latest_version: 0.5.1
add_permalinks: true # adds permalinks to heading tags.
load_disqus: true
